export const GET_CONFIG = "GET_CONFIG";
export const GET_NOWPLAYING_SUCCESS = "GET_NOWPLAYING_SUCCESS";
export const GET_NOWPLAYING_ERROR = "GET_NOWPLAYING_ERROR";
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
export const GET_POPULAR_MOVIES_ERROR = 'GET_POPULAR_MOVIES_ERROR';
export const GET_TOP_RATED_MOVIES_SUCCESS = 'GET_TOP_RATED_MOVIES_SUCCESS';
export const GET_TOP_RATED_MOVIES_ERROR = 'GET_TOP_RATED_MOVIES_ERROR';