export const GET_CONFIG = "GET_CONFIG";
export const GET_NOWPLAYING_SUCCESS = "GET_NOWPLAYING_SUCCESS";
export const GET_NOWPLAYING_ERROR = "GET_NOWPLAYING_ERROR";
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
export const GET_POPULAR_MOVIES_ERROR = 'GET_POPULAR_MOVIES_ERROR';
export const GET_TOP_RATED_MOVIES_SUCCESS = 'GET_TOP_RATED_MOVIES_SUCCESS';
export const GET_TOP_RATED_MOVIES_ERROR = 'GET_TOP_RATED_MOVIES_ERROR';
export const GET_UPCOMING_MOVIES_SUCCESS = 'GET_UPCOMING_MOVIES_SUCCESS';
export const GET_UPCOMING_MOVIES_ERROR = 'GET_UPCOMING_MOVIES_ERROR';
export const GET_SEARCH_MOVIES_SUCCESS = 'GET_SEARCH_MOVIES_SUCCESS';
export const GET_SEARCH_MOVIES_ERROR = 'GET_SEARCH_MOVIES_ERROR';
export const GET_MOVIE_CREDITS_SUCCESS = "GET_MOVIE_CREDITS_SUCCESS";
export const GET_MOVIE_CREDITS_ERROR = "GET_MOVIE_CREDITS_ERROR";
export const GET_MOVIE_TRAILER_SUCCESS = "GET_MOVIE_TRAILER_SUCCESS";
export const GET_MOVIE_TRAILER_ERROR = "GET_MOVIE_TRAILER_ERROR";

