export const GET_CONFIG = "GET_CONFIG";
export const GET_NOWPLAYING_SUCCESS = "GET_NOWPLAYING_SUCCESS";
export const GET_NOWPLAYING_ERROR = "GET_NOWPLAYING_ERROR";
export const GET_LATEST_SUCCESS = 'GET_LATEST_SUCCESS';
export const GET_LATEST_ERROR = 'GET_LATEST_ERROR';
